apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kubesphere
    component: ks-go-sample
    tier: backend
  name: ks-go-sample
  namespace: go-test
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      app: kubesphere
      component: ks-go-sample
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubesphere
        component: ks-go-sample
        tier: backend
    spec:
      containers:
      - image: $REGISTRY/$DOCKERHUB_USERNAME/$APP_NAME:v1
        imagePullPolicy: Always
        name: ks-go
        ports:
        - containerPort: 80
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
